apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamutkart-deployment
  labels:
    env: prod
    version: v1.2.3
spec:
  replicas: 5

  selector:
    matchLabels:
      app: gamutkart

  template:
    metadata:
      labels:
        app: gamutkart
    spec:
      containers:
      - name: gamutkart-server
        image: nageshvkn/gamutkart-img-k8s
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "300m"

        ports:
        - containerPort: 8080
        command: ["/bin/sh"]
        args:  ["-c", "/root/apache-tomcat-8.5.38/bin/startup.sh; while true; do sleep 1; done;"]
        
