apiVersion: v1
kind: Service
metadata:
  name: gamutkart-service
  labels:
    env: prod
    version: v1.2.3
spec:
  type: LoadBalancer
  
  selector:
    app: gamutkart

  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
