pipeline {
	agent any

	environment {
		M2_HOME = ${maven3.6}
	}

	stages {
		stage('Clone-Repo') {
			steps {
				checkout scm
			}
		}
		stage('Build') {
			steps {
				sh "${M2_HOME} install"
			}
		}
		stage('Create-Image') {
			steps {
				sh 'docker build -t="nageshvkn/gamutkart-img" .'
			}
		}
		stage('Create-ENV') {
			steps {
				sh "./create-env.sh 8"
			}
		}
	}
}
