pipeline {
	agent any

	stages {
		stage('Clone-Repo') {
			steps {
				checkout scm
			}
		}
		stage('Build') {
			steps {
				sh "${maven3.6} install"
			}
		}
		stage('Create-Image') {
			steps {
				sh 'docker build -t="nageshvkn/gamutkart-img" .'
			}
		}
		stage('Create-ENV') {
			steps {
				sh "./create-env.sh 8"
			}
		}
	}
}
